// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC91koqQ_B41QquBSBN808T4Q5mftFlpNE',
    appId: '1:573957474693:web:845302b5a632d6117e1cec',
    messagingSenderId: '573957474693',
    projectId: 'emc-tcc-app',
    authDomain: 'emc-tcc-app.firebaseapp.com',
    storageBucket: 'emc-tcc-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1mMNzsibxugy4YFg2KsTqavB30jbwEs',
    appId: '1:573957474693:android:1e195c2296ae00b07e1cec',
    messagingSenderId: '573957474693',
    projectId: 'emc-tcc-app',
    storageBucket: 'emc-tcc-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC91koqQ_B41QquBSBN808T4Q5mftFlpNE',
    appId: '1:573957474693:web:4e41e347a7b955be7e1cec',
    messagingSenderId: '573957474693',
    projectId: 'emc-tcc-app',
    authDomain: 'emc-tcc-app.firebaseapp.com',
    storageBucket: 'emc-tcc-app.firebasestorage.app',
  );
}
